using ChurchYouTubeAssistant.Data;
using ChurchYouTubeAssistant.Models;
using Microsoft.EntityFrameworkCore;

namespace ChurchYouTubeAssistant.Caching;

/// <summary>
/// EF Core / SQL Server implementation of <see cref="IVideoCacheStore"/>.
/// </summary>
/// <remarks>
/// Registered scoped, matching <see cref="ChurchYouTubeAssistantDbContext"/>'s own (default,
/// per-request/per-scope) lifetime.
/// </remarks>
public sealed class EfVideoCacheStore(
    ChurchYouTubeAssistantDbContext db,
    ILogger<EfVideoCacheStore> logger,
    TimeProvider timeProvider) : IVideoCacheStore
{
    public Task<VideoRecord?> GetAsync(string videoId, CancellationToken cancellationToken = default) =>
        db.Videos.AsNoTracking().FirstOrDefaultAsync(v => v.VideoId == videoId, cancellationToken);

    public async Task UpsertAsync(
        string videoId, VideoRecordUpdate update, CancellationToken cancellationToken = default)
    {
        var record = await db.Videos.FirstOrDefaultAsync(v => v.VideoId == videoId, cancellationToken);

        if (record is null)
        {
            record = new VideoRecord { VideoId = videoId, UpdatedAtUtc = timeProvider.GetUtcNow() };
            db.Videos.Add(record);
        }

        // Only overwrite a field when the caller actually supplied one, so a transcript-only update
        // can't wipe out a title cached by an earlier videos-list call, and vice versa.
        if (update.Title is not null) record.Title = update.Title;
        if (update.Description is not null) record.Description = update.Description;
        if (update.PublishedAt is not null) record.PublishedAt = update.PublishedAt;
        if (update.ThumbnailUrl is not null) record.ThumbnailUrl = update.ThumbnailUrl;
        if (update.TranscriptCaptionTrackId is not null) record.TranscriptCaptionTrackId = update.TranscriptCaptionTrackId;
        if (update.TranscriptContent is not null) record.TranscriptContent = update.TranscriptContent;
        if (update.TranscriptLanguage is not null) record.TranscriptLanguage = update.TranscriptLanguage;
        if (update.TranscriptFormat is not null) record.TranscriptFormat = update.TranscriptFormat;
        if (update.TranscriptIsAutoGenerated is not null) record.TranscriptIsAutoGenerated = update.TranscriptIsAutoGenerated;
        if (update.TranscriptFetchedAtUtc is not null) record.TranscriptFetchedAtUtc = update.TranscriptFetchedAtUtc;

        record.UpdatedAtUtc = timeProvider.GetUtcNow();

        await db.SaveChangesAsync(cancellationToken);

        logger.LogDebug("Cached data for video {VideoId} updated.", videoId);
    }
}
