using ChurchYouTubeAssistant.Models;

namespace ChurchYouTubeAssistant.Caching;

/// <summary>
/// Persistence boundary for the per-video cache. <see cref="Services.YouTubeReadService"/> depends
/// on this interface, not on EF Core or <see cref="Data.ChurchYouTubeAssistantDbContext"/> directly,
/// so the storage technology can change without touching the service that uses it - the same
/// seam <see cref="Auth.IYouTubeTokenStore"/> gives the OAuth tokens.
/// </summary>
public interface IVideoCacheStore
{
    /// <summary>Returns the cached record for a video, or null if nothing has been cached yet.</summary>
    Task<VideoRecord?> GetAsync(string videoId, CancellationToken cancellationToken = default);

    /// <summary>
    /// Merges the given fields into the stored record for <paramref name="videoId"/> (creating it if
    /// it doesn't exist yet) and saves it. Only non-null fields on <paramref name="update"/> are
    /// applied, so calling this with just transcript fields does not erase a previously cached title.
    /// </summary>
    Task UpsertAsync(string videoId, VideoRecordUpdate update, CancellationToken cancellationToken = default);
}

/// <summary>
/// The subset of <see cref="VideoRecord"/> a caller wants to write. Every property is optional:
/// null means "leave whatever is already stored alone," not "clear this field."
/// </summary>
public sealed record VideoRecordUpdate
{
    public string? Title { get; init; }
    public string? Description { get; init; }
    public DateTimeOffset? PublishedAt { get; init; }
    public string? ThumbnailUrl { get; init; }

    public string? TranscriptCaptionTrackId { get; init; }
    public string? TranscriptContent { get; init; }
    public string? TranscriptLanguage { get; init; }
    public string? TranscriptFormat { get; init; }
    public bool? TranscriptIsAutoGenerated { get; init; }
    public DateTimeOffset? TranscriptFetchedAtUtc { get; init; }
}
