namespace ChurchYouTubeAssistant.Models;

/// <summary>
/// Our persisted record of one video: what the YouTube Data API told us, cached so repeated reads
/// don't re-spend quota - most importantly the transcript, where captions.list + captions.download
/// together cost 250 of the 10,000 daily quota units.
/// </summary>
/// <remarks>
/// This is a plain EF Core entity (see <see cref="Data.ChurchYouTubeAssistantDbContext"/>), not an
/// API DTO: it is never returned directly from a controller action.
/// </remarks>
public sealed class VideoRecord
{
    /// <summary>The YouTube video id. Primary key - one row per video.</summary>
    public required string VideoId { get; set; }

    public string? Title { get; set; }
    public string? Description { get; set; }
    public DateTimeOffset? PublishedAt { get; set; }
    public string? ThumbnailUrl { get; set; }

    // Transcript fields are null until GetVideoTranscriptAsync has been called for this video at
    // least once. Only one transcript is cached per video: a request for a different language or
    // format than what's stored here bypasses the cache and overwrites it.
    public string? TranscriptCaptionTrackId { get; set; }
    public string? TranscriptContent { get; set; }
    public string? TranscriptLanguage { get; set; }
    public string? TranscriptFormat { get; set; }
    public bool? TranscriptIsAutoGenerated { get; set; }
    public DateTimeOffset? TranscriptFetchedAtUtc { get; set; }

    /// <summary>When this row was last written.</summary>
    public required DateTimeOffset UpdatedAtUtc { get; set; }
}
