namespace ChurchYouTubeAssistant.Models;

/// <summary>The transcript of one video, downloaded from a single caption track.</summary>
public sealed record YouTubeTranscriptDto
{
    public required string VideoId { get; init; }
    public required string CaptionTrackId { get; init; }

    /// <summary>BCP-47 language code of the selected track, e.g. "en" or "ru".</summary>
    public string? Language { get; init; }

    /// <summary>The track's display name, usually empty for the default track of a language.</summary>
    public string? Name { get; init; }

    /// <summary>
    /// True when this track is YouTube's own speech-recognition guess (trackKind "asr") rather than
    /// a manually created or uploaded one. ASR is generally less accurate; prefer a non-ASR track
    /// when one exists in the requested language.
    /// </summary>
    public required bool IsAutoGenerated { get; init; }

    /// <summary>The subtitle format the content was downloaded in: "srt", "vtt" or "sbv".</summary>
    public required string Format { get; init; }

    /// <summary>The raw subtitle file content, including timing codes.</summary>
    public required string Content { get; init; }
}
