using Microsoft.Extensions.Logging;
using ChurchYouTubeAssistant.Ai;
using ChurchYouTubeAssistant.Configuration;
using ChurchYouTubeAssistant.Data;
using ChurchYouTubeAssistant.Exceptions;
using ChurchYouTubeAssistant.Models;
using ChurchYouTubeAssistant.Models.Ai;
using ChurchYouTubeAssistant.Services;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using Moq;
using Xunit;

namespace ChurchYouTubeAssistant.Tests.Ai;

/// <summary>
/// Orchestration tests against a real (SQLite in-memory) DbContext - exercising the actual EF
/// JSON-column mapping rather than assuming it works - with YouTube/OpenAI mocked out, per the
/// spec's instruction to mock external APIs in automated tests.
/// </summary>
public sealed class VideoAnalysisServiceTests : IDisposable
{
    private readonly SqliteConnection _connection;
    private readonly ChurchYouTubeAssistantDbContext _db;
    private readonly Mock<IYouTubeReadService> _readService = new();
    private readonly Mock<IYouTubeWriteService> _writeService = new();
    private readonly Mock<IVideoAnalysisAiService> _aiService = new();
    private readonly Mock<IThumbnailImageService> _thumbnailService = new();
    private readonly Mock<IVideoAnalysisPromptProvider> _promptProvider = new();

    public VideoAnalysisServiceTests()
    {
        _connection = new SqliteConnection("DataSource=:memory:");
        _connection.Open();

        var options = new DbContextOptionsBuilder<ChurchYouTubeAssistantDbContext>()
            .UseSqlite(_connection)
            .Options;

        _db = new ChurchYouTubeAssistantDbContext(options);
        _db.Database.EnsureCreated();

        _promptProvider.SetupGet(p => p.Version).Returns("v1");
    }

    public void Dispose()
    {
        _db.Dispose();
        _connection.Dispose();
    }

    private VideoAnalysisService CreateService() => new(
        _db,
        _readService.Object,
        _writeService.Object,
        _aiService.Object,
        _thumbnailService.Object,
        _promptProvider.Object,
        Options.Create(new OpenAiOptions { ApiKey = "test", Model = "gpt-5" }),
        new VideoAnalysisValidator(),
        TimeProvider.System,
        Mock.Of<ILogger<VideoAnalysisService>>());

    private static YouTubeVideoDto Video(string id, string title, string description, int durationSeconds = 600) => new()
    {
        VideoId = id,
        Title = title,
        Description = description,
        Details = new YouTubeVideoDetailsDto { Duration = TimeSpan.FromSeconds(durationSeconds) }
    };

    private static VideoAnalysisResult MinimalAiResult(string title = "Optimized title", string description = "Optimized description.") => new()
    {
        Language = "ru",
        Metadata = new OptimizedMetadata
        {
            Optimized = new OptimizedTitleDescription { Title = title, Description = description },
            AlternativeTitles = ["Alt 1", "Alt 2", "Alt 3"],
            Reasoning = "reasoning"
        },
        SermonAnalysis = new SermonAnalysis { MainMessage = "msg", MainQuestion = "q?" },
        Thumbnail = new ThumbnailConcept { Headline = "headline" }
    };

    [Fact]
    public async Task AnalyzeAsync_HappyPath_PersistsSucceededAnalysisWithOriginalSnapshot()
    {
        _readService.Setup(s => s.GetVideoAsync("vid1", It.IsAny<CancellationToken>()))
            .ReturnsAsync(Video("vid1", "Original title", "Original description"));
        _readService.Setup(s => s.GetVideoTranscriptAsync("vid1", null, "srt", It.IsAny<CancellationToken>()))
            .ReturnsAsync(new YouTubeTranscriptDto
            {
                VideoId = "vid1", CaptionTrackId = "t1", Format = "srt", Content = "1\n...", IsAutoGenerated = false
            });
        _aiService.Setup(s => s.AnalyzeAsync(It.IsAny<VideoAnalysisInput>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(new VideoAnalysisAiCallResult
            {
                Result = MinimalAiResult(),
                RawResponseJson = "{}",
                Model = "gpt-5",
                PromptVersion = "v1",
                UsedMultiStageFallback = false
            });

        var service = CreateService();
        var analysis = await service.AnalyzeAsync("vid1");

        Assert.Equal(AnalysisStatus.Succeeded, analysis.Status);
        Assert.Equal("Original title", analysis.OriginalTitle);
        Assert.Equal("Optimized title", analysis.OptimizedTitle);
        Assert.NotEqual(Guid.Empty, analysis.Id);

        // Round-trip through the real (SQLite) JSON column mapping.
        var reloaded = await _db.VideoAnalyses.FirstAsync(a => a.Id == analysis.Id);
        Assert.Equal("Optimized title", reloaded.OptimizedTitle);
    }

    [Fact]
    public async Task AnalyzeAsync_AiServiceThrows_RecordsFailedAnalysisAndRethrows()
    {
        _readService.Setup(s => s.GetVideoAsync("vid1", It.IsAny<CancellationToken>()))
            .ReturnsAsync(Video("vid1", "Original title", "Original description"));
        _readService.Setup(s => s.GetVideoTranscriptAsync("vid1", null, "srt", It.IsAny<CancellationToken>()))
            .ReturnsAsync(new YouTubeTranscriptDto
            {
                VideoId = "vid1", CaptionTrackId = "t1", Format = "srt", Content = "1\n...", IsAutoGenerated = false
            });
        _aiService.Setup(s => s.AnalyzeAsync(It.IsAny<VideoAnalysisInput>(), It.IsAny<CancellationToken>()))
            .ThrowsAsync(new AiAnalysisException(AiAnalysisError.RateLimited, "rate limited"));

        var service = CreateService();

        await Assert.ThrowsAsync<AiAnalysisException>(() => service.AnalyzeAsync("vid1"));

        var failed = await _db.VideoAnalyses.FirstAsync(a => a.VideoId == "vid1");
        Assert.Equal(AnalysisStatus.Failed, failed.Status);
        Assert.Contains(failed.Notes, n => n.Contains("rate limited"));
    }

    [Fact]
    public async Task PublishAsync_LiveMetadataUnchanged_PublishesImmediately()
    {
        var analysis = new VideoAnalysis
        {
            Id = Guid.NewGuid(), VideoId = "vid1",
            OriginalTitle = "Original title", OriginalDescription = "Original description.",
            Model = "gpt-5", PromptVersion = "v1", Status = AnalysisStatus.Succeeded, CreatedAtUtc = DateTimeOffset.UtcNow
        };
        _db.VideoAnalyses.Add(analysis);
        await _db.SaveChangesAsync();

        _readService.Setup(s => s.GetVideoAsync("vid1", It.IsAny<CancellationToken>()))
            .ReturnsAsync(Video("vid1", "Original title", "Original description."));

        var service = CreateService();
        var result = await service.PublishAsync(
            "vid1", analysis.Id, new PublishRequest { Title = "New title", Description = "New description." });

        Assert.True(result.Published);
        Assert.False(result.ConflictDetected);
        _writeService.Verify(w => w.UpdateVideoMetadataAsync(
            "vid1", "New title", "New description.", It.IsAny<CancellationToken>()), Times.Once);

        var reloaded = await _db.VideoAnalyses.FirstAsync(a => a.Id == analysis.Id);
        Assert.True(reloaded.IsPublished);
        Assert.Equal("New title", reloaded.PublishedTitle);
    }

    [Fact]
    public async Task PublishAsync_LiveMetadataChangedSinceAnalysis_ReportsConflictWithoutPublishing()
    {
        var analysis = new VideoAnalysis
        {
            Id = Guid.NewGuid(), VideoId = "vid1",
            OriginalTitle = "Original title", OriginalDescription = "Original description.",
            Model = "gpt-5", PromptVersion = "v1", Status = AnalysisStatus.Succeeded, CreatedAtUtc = DateTimeOffset.UtcNow
        };
        _db.VideoAnalyses.Add(analysis);
        await _db.SaveChangesAsync();

        // The live video has since changed - someone edited it on YouTube after this analysis ran.
        _readService.Setup(s => s.GetVideoAsync("vid1", It.IsAny<CancellationToken>()))
            .ReturnsAsync(Video("vid1", "Someone changed this title", "Original description."));

        var service = CreateService();
        var result = await service.PublishAsync(
            "vid1", analysis.Id, new PublishRequest { Title = "New title", Description = "New description." });

        Assert.False(result.Published);
        Assert.True(result.ConflictDetected);
        Assert.Equal("Someone changed this title", result.CurrentLiveTitle);
        _writeService.Verify(w => w.UpdateVideoMetadataAsync(
            It.IsAny<string>(), It.IsAny<string>(), It.IsAny<string>(), It.IsAny<CancellationToken>()), Times.Never);
    }

    [Fact]
    public async Task PublishAsync_ConflictAcknowledged_PublishesAnyway()
    {
        var analysis = new VideoAnalysis
        {
            Id = Guid.NewGuid(), VideoId = "vid1",
            OriginalTitle = "Original title", OriginalDescription = "Original description.",
            Model = "gpt-5", PromptVersion = "v1", Status = AnalysisStatus.Succeeded, CreatedAtUtc = DateTimeOffset.UtcNow
        };
        _db.VideoAnalyses.Add(analysis);
        await _db.SaveChangesAsync();

        _readService.Setup(s => s.GetVideoAsync("vid1", It.IsAny<CancellationToken>()))
            .ReturnsAsync(Video("vid1", "Someone changed this title", "Original description."));

        var service = CreateService();
        var result = await service.PublishAsync(
            "vid1", analysis.Id,
            new PublishRequest { Title = "New title", Description = "New description.", AcknowledgeConflict = true });

        Assert.True(result.Published);
        _writeService.Verify(w => w.UpdateVideoMetadataAsync(
            "vid1", "New title", "New description.", It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task PublishAsync_UnknownAnalysisId_ThrowsNotFound()
    {
        var service = CreateService();

        await Assert.ThrowsAsync<VideoAnalysisNotFoundException>(() =>
            service.PublishAsync("vid1", Guid.NewGuid(), new PublishRequest { Title = "t", Description = "d" }));
    }

    [Fact]
    public async Task SaveThumbnailPromptAsync_SavesPromptWithoutCallingIdeogram()
    {
        var analysis = new VideoAnalysis
        {
            Id = Guid.NewGuid(), VideoId = "vid1", OriginalTitle = "t", OriginalDescription = "d",
            Model = "gpt-5", PromptVersion = "v1", Status = AnalysisStatus.Succeeded, CreatedAtUtc = DateTimeOffset.UtcNow
        };
        _db.VideoAnalyses.Add(analysis);
        await _db.SaveChangesAsync();

        var service = CreateService();
        var result = await service.SaveThumbnailPromptAsync("vid1", analysis.Id, "a draft prompt");

        Assert.Equal("a draft prompt", result.EditedThumbnailPrompt);
        Assert.Null(result.ThumbnailImageData);

        var reloaded = await _db.VideoAnalyses.FirstAsync(a => a.Id == analysis.Id);
        Assert.Equal("a draft prompt", reloaded.EditedThumbnailPrompt);

        _thumbnailService.Verify(
            s => s.GenerateAsync(It.IsAny<string>(), It.IsAny<CancellationToken>()), Times.Never);
    }

    [Fact]
    public async Task GenerateThumbnailImageAsync_SavesEditedPromptBeforeCallingIdeogram()
    {
        var analysis = new VideoAnalysis
        {
            Id = Guid.NewGuid(), VideoId = "vid1", OriginalTitle = "t", OriginalDescription = "d",
            Model = "gpt-5", PromptVersion = "v1", Status = AnalysisStatus.Succeeded, CreatedAtUtc = DateTimeOffset.UtcNow
        };
        _db.VideoAnalyses.Add(analysis);
        await _db.SaveChangesAsync();

        _thumbnailService.Setup(s => s.GenerateAsync("an edited prompt", It.IsAny<CancellationToken>()))
            .ReturnsAsync(new ThumbnailImageResult([1, 2, 3], "image/png"));

        var service = CreateService();
        var result = await service.GenerateThumbnailImageAsync("vid1", analysis.Id, "an edited prompt");

        Assert.Equal("an edited prompt", result.EditedThumbnailPrompt);
        Assert.Equal([1, 2, 3], result.ThumbnailImageData);
        Assert.Equal("image/png", result.ThumbnailImageContentType);
        Assert.NotNull(result.ThumbnailImageGeneratedAtUtc);

        var reloaded = await _db.VideoAnalyses.FirstAsync(a => a.Id == analysis.Id);
        Assert.Equal("an edited prompt", reloaded.EditedThumbnailPrompt);
        Assert.Equal([1, 2, 3], reloaded.ThumbnailImageData);
    }

    [Fact]
    public async Task GenerateThumbnailImageAsync_IdeogramFails_PromptIsStillSavedAndExceptionPropagates()
    {
        var analysis = new VideoAnalysis
        {
            Id = Guid.NewGuid(), VideoId = "vid1", OriginalTitle = "t", OriginalDescription = "d",
            Model = "gpt-5", PromptVersion = "v1", Status = AnalysisStatus.Succeeded, CreatedAtUtc = DateTimeOffset.UtcNow
        };
        _db.VideoAnalyses.Add(analysis);
        await _db.SaveChangesAsync();

        _thumbnailService.Setup(s => s.GenerateAsync(It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .ThrowsAsync(new ThumbnailGenerationException(ThumbnailGenerationError.RateLimited, "rate limited"));

        var service = CreateService();

        await Assert.ThrowsAsync<ThumbnailGenerationException>(() =>
            service.GenerateThumbnailImageAsync("vid1", analysis.Id, "my prompt"));

        // The prompt edit is a separate, earlier write - it must survive even though generation failed.
        var reloaded = await _db.VideoAnalyses.FirstAsync(a => a.Id == analysis.Id);
        Assert.Equal("my prompt", reloaded.EditedThumbnailPrompt);
        Assert.Null(reloaded.ThumbnailImageData);
    }

    [Fact]
    public async Task PublishAsync_WithGeneratedThumbnail_UploadsItAndMarksPublished()
    {
        var analysis = new VideoAnalysis
        {
            Id = Guid.NewGuid(), VideoId = "vid1", OriginalTitle = "Original title", OriginalDescription = "Original description.",
            Model = "gpt-5", PromptVersion = "v1", Status = AnalysisStatus.Succeeded, CreatedAtUtc = DateTimeOffset.UtcNow,
            ThumbnailImageData = [9, 9, 9], ThumbnailImageContentType = "image/png"
        };
        _db.VideoAnalyses.Add(analysis);
        await _db.SaveChangesAsync();

        _readService.Setup(s => s.GetVideoAsync("vid1", It.IsAny<CancellationToken>()))
            .ReturnsAsync(Video("vid1", "Original title", "Original description."));

        var service = CreateService();
        var result = await service.PublishAsync(
            "vid1", analysis.Id, new PublishRequest { Title = "New title", Description = "New description." });

        Assert.True(result.Published);
        Assert.True(result.ThumbnailAttempted);
        Assert.True(result.ThumbnailPublished);
        Assert.Null(result.ThumbnailError);
        _writeService.Verify(w => w.SetThumbnailAsync(
            "vid1", It.Is<byte[]>(b => b.SequenceEqual(new byte[] { 9, 9, 9 })), "image/png", It.IsAny<CancellationToken>()),
            Times.Once);

        var reloaded = await _db.VideoAnalyses.FirstAsync(a => a.Id == analysis.Id);
        Assert.True(reloaded.ThumbnailPublished);
    }

    [Fact]
    public async Task PublishAsync_ThumbnailUploadFails_TitleDescriptionStillPublishedWithErrorReported()
    {
        var analysis = new VideoAnalysis
        {
            Id = Guid.NewGuid(), VideoId = "vid1", OriginalTitle = "Original title", OriginalDescription = "Original description.",
            Model = "gpt-5", PromptVersion = "v1", Status = AnalysisStatus.Succeeded, CreatedAtUtc = DateTimeOffset.UtcNow,
            ThumbnailImageData = [1, 2, 3], ThumbnailImageContentType = "image/png"
        };
        _db.VideoAnalyses.Add(analysis);
        await _db.SaveChangesAsync();

        _readService.Setup(s => s.GetVideoAsync("vid1", It.IsAny<CancellationToken>()))
            .ReturnsAsync(Video("vid1", "Original title", "Original description."));
        _writeService.Setup(w => w.SetThumbnailAsync(
                "vid1", It.IsAny<byte[]>(), It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .ThrowsAsync(new YouTubeIntegrationException("thumbnail upload failed"));

        var service = CreateService();
        var result = await service.PublishAsync(
            "vid1", analysis.Id, new PublishRequest { Title = "New title", Description = "New description." });

        // Title/description must still count as published - a thumbnail failure never masks or
        // rolls back a change YouTube has no way to undo anyway.
        Assert.True(result.Published);
        Assert.True(result.ThumbnailAttempted);
        Assert.False(result.ThumbnailPublished);
        Assert.Equal("thumbnail upload failed", result.ThumbnailError);

        var reloaded = await _db.VideoAnalyses.FirstAsync(a => a.Id == analysis.Id);
        Assert.True(reloaded.IsPublished);
        Assert.False(reloaded.ThumbnailPublished);
    }

    // GetHistoryAsync's "newest first" ordering (OrderByDescending(a => a.CreatedAtUtc)) is not
    // covered here: the EF Core SQLite provider this lightweight test double uses cannot translate
    // ORDER BY over a DateTimeOffset column (a known provider limitation - see
    // https://github.com/dotnet/efcore/issues/26068), while the real target, SQL Server, handles
    // it natively. Adding a SQLite-only value conversion to work around it would mean leaking
    // test-only configuration into the shared DbContext used by production code, which is worse
    // than the gap it would close. This single-column ordering was exercised manually against the
    // real local SQL Server database during development.
}
