// <auto-generated />
using System;
using ChurchYouTubeAssistant.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChurchYouTubeAssistant.Migrations
{
    [DbContext(typeof(ChurchYouTubeAssistantDbContext))]
    [Migration("20261007150350_AddThumbnailImage")]
    partial class AddThumbnailImage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChurchYouTubeAssistant.Models.VideoAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlternativeTitles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EditedDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EditedThumbnailPrompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EditedTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("KeyThemes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MainMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainQuestion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptimizedDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptimizedTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("int");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PublishedDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublishedTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawOpenAiResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ThumbnailImageContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("ThumbnailImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTimeOffset?>("ThumbnailImageGeneratedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("ThumbnailPublished")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ThumbnailPublishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TitleReasoning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("int");

                    b.Property<bool>("UsedMultiStageFallback")
                        .HasColumnType("bit");

                    b.Property<int?>("VideoDurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("VideoId", "CreatedAtUtc");

                    b.ToTable("VideoAnalyses", (string)null);
                });

            modelBuilder.Entity("ChurchYouTubeAssistant.Models.VideoRecord", b =>
                {
                    b.Property<string>("VideoId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TranscriptCaptionTrackId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TranscriptContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("TranscriptFetchedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TranscriptFormat")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool?>("TranscriptIsAutoGenerated")
                        .HasColumnType("bit");

                    b.Property<string>("TranscriptLanguage")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("VideoId");

                    b.ToTable("Videos", (string)null);
                });

            modelBuilder.Entity("ChurchYouTubeAssistant.Models.VideoAnalysis", b =>
                {
                    b.OwnsMany("ChurchYouTubeAssistant.Models.Ai.BibleReferenceInfo", "BibleReferences", b1 =>
                        {
                            b1.Property<Guid>("VideoAnalysisId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Context")
                                .IsRequired()
                                .HasJsonPropertyName("context");

                            b1.Property<bool>("IsPrimary")
                                .HasJsonPropertyName("isPrimary");

                            b1.Property<string>("Reference")
                                .IsRequired()
                                .HasJsonPropertyName("reference");

                            b1.Property<string>("ReferenceType")
                                .IsRequired()
                                .HasJsonPropertyName("referenceType");

                            b1.Property<int?>("StartSeconds")
                                .HasJsonPropertyName("startSeconds");

                            b1.HasKey("VideoAnalysisId", "__synthesizedOrdinal");

                            b1.ToTable("VideoAnalyses");

                            b1
                                .ToJson("BibleReferences")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("VideoAnalysisId");
                        });

                    b.OwnsMany("ChurchYouTubeAssistant.Models.Ai.ChapterInfo", "Chapters", b1 =>
                        {
                            b1.Property<Guid>("VideoAnalysisId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<bool>("Included")
                                .HasJsonPropertyName("included");

                            b1.Property<int>("StartSeconds")
                                .HasJsonPropertyName("startSeconds");

                            b1.Property<string>("StartTime")
                                .IsRequired()
                                .HasJsonPropertyName("startTime");

                            b1.Property<string>("Summary")
                                .IsRequired()
                                .HasJsonPropertyName("summary");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasJsonPropertyName("title");

                            b1.HasKey("VideoAnalysisId", "__synthesizedOrdinal");

                            b1.ToTable("VideoAnalyses");

                            b1
                                .ToJson("Chapters")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("VideoAnalysisId");
                        });

                    b.OwnsMany("ChurchYouTubeAssistant.Models.Ai.ShortCandidate", "Shorts", b1 =>
                        {
                            b1.Property<Guid>("VideoAnalysisId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Category")
                                .IsRequired()
                                .HasJsonPropertyName("category");

                            b1.Property<string>("Conclusion")
                                .IsRequired()
                                .HasJsonPropertyName("conclusion");

                            b1.Property<int>("DurationSeconds")
                                .HasJsonPropertyName("durationSeconds");

                            b1.Property<int>("EndSeconds")
                                .HasJsonPropertyName("endSeconds");

                            b1.Property<string>("EndTime")
                                .IsRequired()
                                .HasJsonPropertyName("endTime");

                            b1.Property<string>("Hook")
                                .IsRequired()
                                .HasJsonPropertyName("hook");

                            b1.Property<string>("MainMessage")
                                .IsRequired()
                                .HasJsonPropertyName("mainMessage");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasJsonPropertyName("reason");

                            b1.Property<bool>("RequiresManualReview")
                                .HasJsonPropertyName("requiresManualReview");

                            b1.Property<int>("Score")
                                .HasJsonPropertyName("score");

                            b1.Property<int>("StartSeconds")
                                .HasJsonPropertyName("startSeconds");

                            b1.Property<string>("StartTime")
                                .IsRequired()
                                .HasJsonPropertyName("startTime");

                            b1.Property<string>("TimestampConfidence")
                                .IsRequired()
                                .HasJsonPropertyName("timestampConfidence");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasJsonPropertyName("title");

                            b1.Property<string>("TranscriptExcerpt")
                                .IsRequired()
                                .HasJsonPropertyName("transcriptExcerpt");

                            b1.HasKey("VideoAnalysisId", "__synthesizedOrdinal");

                            b1.ToTable("VideoAnalyses");

                            b1
                                .ToJson("Shorts")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("VideoAnalysisId");
                        });

                    b.OwnsOne("ChurchYouTubeAssistant.Models.Ai.ThumbnailConcept", "Thumbnail", b1 =>
                        {
                            b1.Property<Guid>("VideoAnalysisId");

                            b1.PrimitiveCollection<string>("AlternativeHeadlines")
                                .IsRequired()
                                .HasJsonPropertyName("alternativeHeadlines");

                            b1.Property<string>("Composition")
                                .IsRequired()
                                .HasJsonPropertyName("composition");

                            b1.Property<string>("Headline")
                                .IsRequired()
                                .HasJsonPropertyName("headline");

                            b1.Property<string>("ImagePrompt")
                                .IsRequired()
                                .HasJsonPropertyName("imagePrompt");

                            b1.Property<string>("Reasoning")
                                .IsRequired()
                                .HasJsonPropertyName("reasoning");

                            b1.Property<string>("VisualConcept")
                                .IsRequired()
                                .HasJsonPropertyName("visualConcept");

                            b1.HasKey("VideoAnalysisId");

                            b1.ToTable("VideoAnalyses");

                            b1
                                .ToJson("Thumbnail")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("VideoAnalysisId");
                        });

                    b.Navigation("BibleReferences");

                    b.Navigation("Chapters");

                    b.Navigation("Shorts");

                    b.Navigation("Thumbnail");
                });
#pragma warning restore 612, 618
        }
    }
}
