using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ChurchYouTubeAssistant.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Videos",
                columns: table => new
                {
                    VideoId = table.Column<string>(type: "nvarchar(32)", maxLength: 32, nullable: false),
                    Title = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                    Description = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PublishedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                    ThumbnailUrl = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                    TranscriptCaptionTrackId = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    TranscriptContent = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TranscriptLanguage = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    TranscriptFormat = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    TranscriptIsAutoGenerated = table.Column<bool>(type: "bit", nullable: true),
                    TranscriptFetchedAtUtc = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                    UpdatedAtUtc = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Videos", x => x.VideoId);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Videos");
        }
    }
}
